### ISSUE TITLE
routes.js refers to local disk

### ISSUE THREAD

**Issue by djdjoko** [asyncapi/nodejs-ws-template#103]
When i build the nodejs template using:

ag asyncapi.yml @asyncapi/nodejs-ws-template -o nodejs -p server=localhost --force-write

the code generates a link to the local disk 'C:\'. Not sure if I am building it wrong. 

Thanks

```
router.ws('C:\subscribe\test', async (ws, req) => {
 
});
```

**Comment by magicmatatjahu** [comment]
@djdjoko Hi! Thanks for issue! As I see in the source code we have logic to generate `router/ws` [here](https://github.com/asyncapi/nodejs-ws-template/blob/2cde65701e6a15ac72dc7db2c216d25377cd5333/template/src/api/routes.js#L12). As you can see we transform the channelName by [`pathResolve` function](https://github.com/asyncapi/nodejs-ws-template/blob/2cde65701e6a15ac72dc7db2c216d25377cd5333/filters/all.js#L12). Probably you are using the Windows and due to this, the NodeJS's `path` module transform path to the absolute with `C:` as the prefix.

**Comment by derberg** [comment]
@djdjoko can you share asyncapi file that you were using?

**Comment by Krishks369** [comment]
@derberg What do you think of this code
```
function pathResolve(pathName, basePath = '/') {
   if(pathName.startsWith("/")){
  return pathName;
  }
  else{
    p = path.resolve(pathName).replace(/C:\\/g, '/');
  return p;
  }```
should I be more general instead of replacing "C:" in the code? like if the directory was "D"

**Comment by derberg** [comment]
fixed with https://github.com/asyncapi/nodejs-ws-template/pull/149
