### ISSUE TITLE
Multiple messages are not supported

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/nodejs-ws-template#66]
#### Describe the bug
The spec defines that an operation may define multiple messages, however, we always only use 1 message regardless.

#### How to Reproduce
Provide the following document:
```json
{
  "asyncapi": "2.0.0",
  "info": {
    "title": "Streetlight",
    "version": "1.0.0"
  },
  "defaultContentType": "json",
  "channels": {
    "streetlight": {
      "publish": {
        "message": {
          "oneOf": [
            {
              "payload": {
                "type": "integer"
              }
            },
            {
              "payload": {
                "type": "string"
              }
            }
          ]
        }
      }
    }
  }
}
```

#### Expected behavior
Expected it to handle multiple messages.

**Comment by joerg-walter-de** [comment]
Since it may be very reasonable to send multiple different messages through one channel but I am only able to specify an operation ID per channel, I am forced to put the discrimination logic into the channel operation. I think, an (optional) operation ID per message may be more flexible.

I haven't explored the generator/validator aspects of AsyncAPI in total. I am used to generate client code for OpenAPI specs, that is for example callable JS functions where the function names match the operationId s and the functions provide datagram / parameter validation. And obviously it would be nice for a client to be able to call sendPing(), subscribeToData() etc. that is, to have a send-function for each possible message. Having a operationId for each message would help achieving that, I guess.

**Comment by derberg** [comment]
still relevant, just better to first rewrite template to React
